# Architecture
arch: ResNet18
task: dense

# ===== Dataset ===== #
data: /home/tangpw/FairSurrogates/
set: CelebA
name: ResNet18_dense_celeba

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.01
lr_policy: cosine_lr
loss: BCEWithLogitsLoss

# ===== Network training config ===== #
epochs: 3
weight_decay: 0.0001
momentum: 0.9
batch_size: 128

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
mode: fan_in
nonlinearity: relu
prune_rate: 1

# ===== Hardware setup ===== #
workers: 4